In [1]:
from pylibCZIrw import czi as pyczi
import json
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np
import os, sys
from tqdm import tqdm
from tqdm.contrib import itertools as it
from matplotlib.patches import Rectangle

ModuleNotFoundError: No module named 'pylibCZIrw'

In [6]:
# define the filename
czifile_5dstack = os.path.join("Filemail.com files 11_29_2023 intruplnqutxbah", r"2022_06_17__RecognizedCode.czi")

# open the CZI for reading using a context manager (preferred way to do it)
with pyczi.open_czi(czifile_5dstack) as czidoc:
    # get the raw metadata as XML
    md_xml = czidoc.raw_metadata
    print(md_xml)
    


<?xml version="1.0"?>
<ImageDocument>
 <Metadata>
  <Experiment Version="1.2">
   <RunMode>ValidateAndAdaptBeforePerformEnabled,PreventMissingCalibrationDataInformation,PreventStageXYRestoreAfterExperiment,PreventFocusRestoreAfterExperiment</RunMode>
   <BeforeHardwareSetting>HardwareBefore</BeforeHardwareSetting>
   <AfterHardwareSetting>HardwareAfter</AfterHardwareSetting>
   <ExperimentBlockIndex>0</ExperimentBlockIndex>
   <IsSegmented>false</IsSegmented>
   <IsStandardMode>true</IsStandardMode>
   <ImageName>D:\DATA\Cirqle\20220617\2022_06_17__RecognizedCode.czi</ImageName>
   <ImageTransferMode>MemoryMappedAndFileStream</ImageTransferMode>
   <AutoSave IsActivated="false" EnableSingleFileSave="false">
    <StorageFolder>C:\Users\zeiss-service\Pictures</StorageFolder>
    <Name>New</Name>
    <IsAutoSubFolder>true</IsAutoSubFolder>
    <AlwaysAddFileIndex>true</AlwaysAddFileIndex>
    <IsAutoSubFolderExternal>true</IsAutoSubFolderExternal>
    <IsClosedOnCompletion>false</IsClosed

In [7]:
# Define the filename
czifile_5dstack = os.path.join("Filemail.com files 11_29_2023 intruplnqutxbah", r"2022_06_17__RecognizedCode.czi")

# Open the CZI for reading using a context manager (preferred way to do it)
with pyczi.open_czi(czifile_5dstack) as czidoc:
    # Get pixel data using the Single Channel Scaling Accessor
    pixel_data = czidoc.read()

# Display information about the NumPy array
print("Shape of the NumPy array:", pixel_data.shape)
print("Data type of the NumPy array:", pixel_data.dtype)



Shape of the NumPy array: (19584, 18888, 3)
Data type of the NumPy array: uint8


In [12]:
# Assuming 'pixel_data' is your NumPy array
middle_x = pixel_data.shape[1] // 2
middle_y = pixel_data.shape[0] // 2

# Extract a 10x10 region of RGB values centered around the middle of the image
start_x = middle_x - 5
end_x = middle_x + 5
start_y = middle_y - 5
end_y = middle_y + 5

# Ensure the region is within the image boundaries
start_x = max(0, start_x)
end_x = min(pixel_data.shape[1], end_x)
start_y = max(0, start_y)
end_y = min(pixel_data.shape[0], end_y)

# Extract the RGB values in the specified region
rgb_matrix = pixel_data[start_y:end_y, start_x:end_x, :]

# Display the RGB values as a 10x10 matrix
print("RGB Values in a 10x10 region around the middle of the image:")
print(rgb_matrix.reshape(10, 10, 3))


RGB Values in a 10x10 region around the middle of the image:
[[[ 63  88 121]
  [ 64  83 114]
  [ 71  90 118]
  [ 83 103 129]
  [ 83 113 147]
  [ 79 114 152]
  [ 80 105 138]
  [ 79  94 128]
  [ 82 100 132]
  [ 83 115 143]]

 [[ 74 100 130]
  [ 76  96 124]
  [ 78  98 125]
  [ 90 112 140]
  [ 81 111 147]
  [ 71 105 142]
  [ 76 104 138]
  [ 76 101 138]
  [ 81 109 144]
  [ 79 119 150]]

 [[ 84 112 143]
  [ 91 113 140]
  [ 88 112 140]
  [ 97 127 163]
  [ 88 125 167]
  [ 75 110 150]
  [ 75 107 146]
  [ 74 107 154]
  [ 74 105 148]
  [ 72 106 141]]

 [[ 90 123 158]
  [ 95 126 160]
  [ 87 119 154]
  [ 85 122 164]
  [ 77 115 159]
  [ 74 107 146]
  [ 76 108 149]
  [ 70 107 158]
  [ 64  95 141]
  [ 63  90 126]]

 [[ 89 126 167]
  [ 86 127 170]
  [ 76 118 161]
  [ 68 108 150]
  [ 59  95 133]
  [ 64  94 126]
  [ 74 104 139]
  [ 72 107 151]
  [ 69  96 136]
  [ 70  90 124]]

 [[ 80 117 160]
  [ 76 116 163]
  [ 71 110 157]
  [ 65 101 143]
  [ 58  87 124]
  [ 61  86 120]
  [ 71  98 134]
  [ 74 105 143]
 

In [8]:
with pyczi.open_czi(czifile_5dstack) as czidoc:

    # get the image dimensions as an dictionary, where the key identifies the dimension
    total_bounding_box = czidoc.total_bounding_box

print(total_bounding_box)

read(**kwargs)

{'T': (0, 1), 'Z': (0, 1), 'C': (0, 1), 'X': (-87848, -68960), 'Y': (17280, 36864)}


NameError: name 'read' is not defined

In [ ]:
with pyczi.open_czi(czifile_scenes) as czidoc:

    # get the total bounding box for all scenes
    total_bounding_rectangle = czidoc.total_bounding_rectangle

print(total_bounding_rectangle)


Rectangle(x=-87848, y=17280, w=18888, h=19584)


In [ ]:
with pyczi.open_czi(czifile_scenes) as czidoc:
    
    # get the pixel type for the 1st channel
    c0_pixel_type = czidoc.get_channel_pixel_type(0)

print(c0_pixel_type)


Bgr24


In [ ]:
with pyczi.open_czi(czifile_scenes) as czidoc:
    
    # get all pixel types as a dictionary, where the key is the channel index
    pixel_type = czidoc.pixel_types

print(pixel_type)

{0: 'Bgr24'}


In [ ]:
with pyczi.open_czi(czifile_5dstack) as czidoc:

    # define some plane coordinates
    plane_1 = {'C': 0, 'Z': 2, 'T': 1}
    plane_2 = {'C': 1, 'Z': 3, 'T': 2}

    # equivalent to reading {'C': 0, 'Z': 0, 'T': 0}
    frame_0 = czidoc.read()

    # get the shape of the 2d plane - the last dime indicates the pixel type
    # 3 = BGR and 1 = Gray
    print("Array Shape: ", frame_0.shape)

    # get specific planes 
    frame_1 = czidoc.read(plane=plane_1)
    frame_2 = czidoc.read(plane=plane_2)

fig, ax = plt.subplots(1, 3, figsize=(15, 5))
ax[0].imshow(frame_0[...,0], cmap=cm.inferno)
ax[0].set_title("Frame_0")
ax[1].imshow(frame_1[...,0], cmap=cm.inferno)
ax[1].set_title("Frame_1")
ax[2].imshow(frame_2[...,0], cmap=cm.Greens_r)
ax[2].set_title("Frame_2")

Array Shape:  (19584, 18888, 3)


ValueError: The pixel type provided does not mach any supported pixel types, possible values are: Gray8, Gray16, Gray32Float, Bgr24, Bgr48, Bgr96Float